### ISSUE TITLE
Error: Can't resolve '@cmdap/ng-wizard/lib/ng-wizard.service'

### ISSUE THREAD

**Issue by Paul75** [cmdap/ng-wizard#13]
Hello,

When Implemet got error : Error: Can't resolve '@cmdap/ng-wizard/lib/ng-wizard.service'

Thanks

**Comment by jbrems** [comment]
Hi Paul,

What version of Angular are you using?

**Comment by Paul75** [comment]
Hello,

I am using Angular 9

**Comment by jbrems** [comment]
Hi @Paul75 ,

I'm very sorry for this late response but I finally found some time to look into your issue.
It appears that you added the `NgWizardService` to your `providers` array and Angular tells you that service is not exported by our package. Is that correct?
If so, this issue can be resolved by adding `NgWizardModule` to your app's `imports` array (and removing `NgWizardService` from your providers).

I will add this to the README.
