### ISSUE TITLE
Wizard is not working in child module

### ISSUE THREAD

**Issue by abidalis** [cmdap/ng-wizard#15]
Hello,

I have child module "Event" and I want to make wizard in event module not in app module. I did configure as you mentioned in the [cmdap/ng-wizard](https://github.com/cmdap/ng-wizard) but it's not working.

Here is child route

`const routes: Routes = [
  { path: '', component: NgWizardComponent, children: [
      { path: 'location', component: Step1Component },
      { path: 'schedule', component: Step2Component },
      { path: 'items', component: Step3Component },
      { path: '**', redirectTo: 'location' },
  ], data: { name: 'myWizard' }},
  { path: '**', redirectTo: '' },
];`

Here is the route in appmodule routing file.

`const appRoutes: Routes = [
  // tslint:disable-next-line:max-line-length
  { path: '', component: FullLayoutComponent, canActivate: [AuthGuard], canActivateChild: [RoleGuard],  data: { expectedRole: 'customer'}, children: SECURE_ROUTES },
 // { path: '', component: FullLayoutComponent, children: SECURE_ROUTES },
 { path: '', component: SimpleLayoutComponent, children: PUBLIC_ROUTES },
 { path: '', component: FullLayoutComponent, children: PUBLIC_ROUTES_FL },
 

> { path : 'event', component: FullLayoutComponent, loadChildren : () => import('./event/event.module').then(m => m.EventModule)},

 { path: '**', redirectTo: 'index.html' }
];`

Notice, I'm using layout component to load the content.

After debugging, I came to know that when it filter the "NgWizardComponent" from route data, it's not finding it because on top of NzWizardComponent there is a FullLayoutComponent. Check the screenshot below.

![image](https://user-images.githubusercontent.com/27686570/97411762-b3bea700-1926-11eb-8ee0-fa1d0df1782a.png)

Please let me know how to fix this.

Thanks,
AbidAli

**Comment by maxgaj** [comment]
Hello @abidalis 

I've released version 10.0.0 that will work with your configuration.
Can you upgrade to this new version and let us know that is working for you?

**Comment by abidalis** [comment]
Hi @maxgaj 

Thanks for quick response.

As you told, I have updated it to v10 but it's not working. I have noticed that you have made changes in package version and readme file only. Seems like you have missed something to be pushed.

Thanks,
AbidAli

**Comment by abidalis** [comment]
> Hi @maxgaj
> 
> Thanks for quick response.
> 
> As you told, I have updated it to v10 but it's not working. I have noticed that you have made changes in package version and readme file only. Seems like you have missed something to be pushed.
> 
> Thanks,
> AbidAli

@maxgaj Do you have any resolution of this?

**Comment by waltersajtos** [comment]
Do you guys plan on fixing this?

**Comment by jbrems** [comment]
Do you have an example repository I can clone to investigate the issue?

**Comment by waltersajtos** [comment]
I do! https://github.com/digitalExcellence/dex-frontend/tree/361-implement-wizard
The wizard module is located at src>app>modules>project>add>main>wizard

**Comment by jbrems** [comment]
Hi @waltersajtos,

Thanks for providing your repository (your project looks awesome by the way :) ).
With the help of your project I figured out our Wizard component did not support lazily loaded child routes.
I published a quick (and a little bit dirty) fix in version `10.1.0`.
Please upgrade your dependency and let us know if you have any further issues.

PS: Make sure to redirect the user to the first step of the wizard as a fallback route;
https://github.com/DigitalExcellence/dex-frontend/blob/85dfcb88641889e4c3004d3e4a0a6222873dac7e/src/app/modules/project/add/main/wizard/wizard-routing.module.ts#L44
should be `{path: '**', redirectTo: 'username'},` in your project.

**Comment by jbrems** [comment]
@abidalis version `10.1.0` should also resolve your issue.
