### ISSUE TITLE
Enable dynamic routing

### ISSUE THREAD

**Issue by waltersajtos** [cmdap/ng-wizard#17]
I've seen that this is included in the planned improvements in the README.md. Is the implementation planned already? I want to be able to change the steps that the user goes through, right now it automatically goes through all the steps that are in the router modules.

**Comment by jbrems** [comment]
Hi @waltersajtos 

The planned improvements slowly transitioned into a wish list over time and will probably not be implemented anytime soon.
I will remove the planned improvements list from the readme to avoid confusion.

For your use case you might want to try to use a step´s ngOnInit to skip it (redirect to the next step) when desired. The navigation menu can be altered with a bit of CSS. I hope you can find a workaround for this missing feature.

Regards,
Jonas
